export const CARD_ACTION = {
  CARD_ACTION_ADD_CARD: 'CARD_ACTION_ADD_CARD',
  CARD_ACTION_DELETE_CARD: 'CARD_ACTION_DELETE_CARD',
  CARD_ACTION_SHOW_ADD_CLIENT: 'CARD_ACTION_SHOW_ADD_CLIENT',
  CARD_ACTION_CHANGE_DEFAULT_CARD: 'CARD_ACTION_CHANGE_DEFAULT_CARD',
  CARD_ACTION_CHANGE_DEFAULT_CARD_OK: 'CARD_ACTION_CHANGE_DEFAULT_CARD_OK',
  CARD_ACTION_HANDLE_INFO_CARD: 'CARD_ACTION_HANDLE_INFO_CARD',
  CARD_ACTION_UPDATE_CLIENTS: 'CARD_ACTION_UPDATE_CLIENTS',
}

export const RESET_VALUES_ACTION = {
  RESET_VALUES: 'RESET_VALUES_ACTION_RESET_VALUES'
}
